### ISSUE TITLE
Program closing before starting a search

### ISSUE THREAD

**Issue by AceMuffins** [Wulfre/e621dl#29]
When i opened the program, it showed some text and then immediately closed, i managed to screencap the text it was printing
![asdasdasd](https://user-images.githubusercontent.com/36843738/51053619-d31a0200-15e2-11e9-84ea-d5354853edc2.png)

**Comment by Wulfre** [comment]
Can I have more information about your system? I tried to look at the issue to see if maybe my user-agent was blocked, but the latest exe that I released still works for me.

**Comment by Zenliss** [comment]
System? if you mean the Windows version, its windows 10 Pro, if its not that, then please elaborate further
Also, just to note, ive succesfully ran e621dl several days ago

**Comment by Zenliss** [comment]
I also just tried with the source version, not the exe version, still the same result

**Comment by xzyxzy** [comment]
Implement cloudflare cookies?

**Comment by Zenliss** [comment]
And how would I do that?

**Comment by lurkbbs** [comment]
Technically, it _might_ be possible:
1. Search for recaptcha `<form>` tag, then for iframe tag, then printing adress to terminal
2. Open recaptcha address, then solving it, then copying response text
3. Pasting in back to the script and sending post request whenever `form` says to post
4. Repeat until recaptcha is solved

I'll try to solve it these weekends if there still be Cloudflare protection.

P.S. Can anyone tell how to grammatically correctly say "I'll do X if there still be Y"? Tenses around _if_ are somewhat counterintuitive for non-native speakers like me.

**Comment by Zenliss** [comment]
I.... Didn't understand a word in what you just said, not that you wrote it wrong, but I don't know anything about how recaptcha and the program itself works

**Comment by lurkbbs** [comment]
Don't worry, that's technical details on how to change a code.

Just wait till next Monday: either I solve it, or it solves itself. Or somebody else will. Or will turn out to be impossible to solve. So wait here for updates and (hopefully) a patch/pull request.

**Comment by lurkbbs** [comment]
Watashi ga kita! Way before the Monday. Here is the pull request: https://github.com/Wulfre/e621dl/pull/30
Here is direct updated version download: https://github.com/lurkbbs/e621dl/archive/patch-1.zip

Sadly, it won't "just work" and completely bypass recaptcha. You will need to install Referer Control to your browser (or browser, if you are not using either Firefox and Chrome). Here is temporary settings you need for recaptcha to work:

![Referer Control settings](https://user-images.githubusercontent.com/38856256/51419442-97aba480-1b9b-11e9-80fd-cc75f763fa09.png)

Now, if you really have a problem with Cloudflare, you should see something like this:
![e621dl recaptcha code prompt](https://user-images.githubusercontent.com/38856256/51419718-b4e17280-1b9d-11e9-83b4-70ade27dc852.png)

So you open `https://www.google.com/recaptcha/api/fallback?k=DigitsAndLettersAsAlways` in you browser and solve a captcha:
![NoScript Captcha](https://user-images.githubusercontent.com/38856256/51419861-d4c56600-1b9e-11e9-9491-5747ea3ab1fe.png)

Here is text you'll get for your trouble:
![Recaptcha confirmation text](https://user-images.githubusercontent.com/38856256/51419960-967c7680-1b9f-11e9-8f49-05ae47f71f0e.png)

After you copy it and if His Divine Shadow is generous, e621dl should work as usual:
![Cloudflare is satisfied](https://user-images.githubusercontent.com/38856256/51420008-ea875b00-1b9f-11e9-84b7-40f28ae46ece.png)

That's it. @Zenliss , thank you for bringing it to my attention. I was in doubt if it was Cloudflare or my fork blocked. Now I know it's just DDOS overprotection.

**Comment by Zenliss** [comment]
@lurkbbs thanks, but it seems that there is some other issue present, ive downloaded the build you mentioned, and tested out the program on the default tags:
![default](https://user-images.githubusercontent.com/36843738/51425300-ce58dd80-1be2-11e9-86fa-1878123e4ac7.png)
and, well, here are the results:
![default](https://user-images.githubusercontent.com/36843738/51425317-08c27a80-1be3-11e9-8af5-9defde072102.png)
At this point, i have no idea whats wrong with my attempts, maybe i dont have something python related installed. maybe it just wont work in my system, but it worked before, and now it doesnt

**Comment by lurkbbs** [comment]
Fixed, same link: https://github.com/lurkbbs/e621dl/archive/patch-1.zip
This time I _actually_ checked if it works.

Wow. Three people make three various-sized mistakes
1. Me. Captcha solver code worked, but check status was inverted. That is, if captcha solved successfully, code said it's not and vise versa. Yes, last minute untested changes. Shame.
2. Wulfre. On empty blacklist with modern `pip install pyyaml` config parser failed.
3. Zenliss. _Default_ default config is correct:

```
toggles:
    include_md5: false

default_search:
    days: 1
    min_score: 0
    min_favs: 0
    ratings:
        - s

blacklist:
    
searches:
    cats:
        tags:
            - cat
            - yellow_fur
    dogs:
        tags:
            - dog
            - brown_fur

# The most common search structure has already been exemplified, but you may overwrite any of the default search settings for a specific search.
#
# searches:
#   dogs:
#       days: 30
#       min_score: 10
#       min_favs: 10
#       ratings:
#           -s
#           -q
#           -e
#       tags:
#           - dog
#           - brown_fur
```

Alternative is correct too: 

```
toggles:
    include_md5: false

default_search:
    days: 1
    min_score: 0
    min_favs: 0
    ratings:
        - s

blacklist:
    
# searches:
#     cats:
#         tags:
#             - cat
#             - yellow_fur
#     dogs:
#         tags:
#             - dog
#             - brown_fur

# The most common search structure has already been exemplified, but you may overwrite any of the default search settings for a specific search.
#
searches:
  dogs:
      days: 30
      min_score: 10
      min_favs: 10
      ratings:
          -s
          -q
          -e
      tags:
          - dog
          - brown_fur
```

But there can't be multiple definitions of the same tag, `dogs` here
