### ISSUE TITLE
Task Scheduler doesn't run the right searches.

### ISSUE THREAD

**Issue by darkspyro92** [Wulfre/e621dl#43]
So I set up my Task Scheduler to automatically run e621dl, but it runs the default searches instead of my searches. I added the number signs before the default searches thinking that was the problem, but that didn't change anything.

**config.yaml:**

# Note that if you included your auth above, then your account blacklist will already be applied.
blacklist:
```

search_defaults:
    days: 999999999999999999999
    min_score: 0
    min_fav_count: 0
    allowed_ratings:
        - e

#searches:
#    cats:
#        tags:
#            - cat
#            - yellow_fur
#    dogs:
#        tags:
#            - dog
#            - brown_fur
#
# The most common search structure has already been exemplified, but you may overwrite any of the default search settings for a specific search.
#
# searches:
#   dogs:
#       days: 30
#       min_score: 10
#       min_fav_count: 10
#       allowed_ratings:
#           - s
#           - q
#           - e
#       tags:
#           - dog
#           - brown_fur

searches:
    Latias:
        days: 2
        tags:
            - latias
    Ember Spyro:
        days: 2
        tags:
            - ember_(spyro)
```

![e621dlTSE](https://user-images.githubusercontent.com/22324730/80719542-a0429880-8ac9-11ea-8199-d7acedfed340.png)
![e621dlTSE2](https://user-images.githubusercontent.com/22324730/80719545-a173c580-8ac9-11ea-8475-0e58be8073d8.png)
![e621dlTSE3](https://user-images.githubusercontent.com/22324730/80719546-a20c5c00-8ac9-11ea-907c-fb1e42c064bd.png)
